name: quickcheck-special
version: 0.1.0.3
synopsis: Edge cases and special values for QuickCheck Arbitrary instances
description:
  The standard Arbitrary instances of QuickCheck don't generate
  special values. This is fixed by this package which provides the newtype Special
  with an Arbitrary instance. The special values are given by the SpecialValues typeclass.
category: Testing
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2016 Daniel Mendler
license: MIT
github: minad/quickcheck-special

ghc-options:
- -Wall

dependencies:
- base < 6
- bytestring >= 0.9 && < 0.11
- QuickCheck >= 2.1 && < 2.10
- scientific >= 0.2 && < 0.4
- text       >= 0.7 && < 1.3
- ieee754    >= 0.8 && < 0.9

when:
  - condition: impl(ghc < 7.10)
    dependencies: nats >= 1

tested-with:
  GHC == 7.0.4,
  GHC == 7.2.2,
  GHC == 7.4.2,
  GHC == 7.6.3,
  GHC == 7.8.4,
  GHC == 7.10.3,
  GHC == 8.0.1

library:
  source-dirs: src
