name: special-values
version: 0.1.0.0
synopsis: Typeclass providing special values
description:
  Special values are provided by a SpecialValues typeclass.
  Those can be used for example by QuickCheck, see quickcheck-special.
category: Testing
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2017 Daniel Mendler
license: MIT
github: minad/special-values

ghc-options:
- -Wall

dependencies:
- base < 6
- bytestring >= 0.9 && < 0.12
- scientific >= 0.2 && < 0.4
- text       >= 0.7 && < 1.3
- ieee754    >= 0.8 && < 0.9

when:
  - condition: impl(ghc < 7.10)
    dependencies: nats >= 1

tested-with:
  GHC == 7.2.2,
  GHC == 7.4.2,
  GHC == 7.6.3,
  GHC == 7.8.4,
  GHC == 7.10.3,
  GHC == 8.0.2,
  GHC == 8.2.2,
  GHC == 8.4.4,
  GHC == 8.6.5,
  GHC == 8.8.4,
  GHC == 8.10.7,
  GHC == 9.0.1,
  GHC == 9.2.1

library:
  source-dirs: src
